### ISSUE TITLE
Wrong type in Entity corridor

### ISSUE THREAD

**Issue by IvanLudvig** [reearth/resium#453]
There's a type error when creating an Entity with a corridor. Creating an Entity like this (from a Cesium sandcastle [demo](https://sandcastle.cesium.com/index.html?src=Corridor.html)).
```javascript
<Entity
    position={Cartesian3.fromDegrees(20, 20)}
    corridor={{
        positions: Cartesian3.fromDegreesArray([
            -100.0, 40.0,
            -105.0, 40.0,
            -105.0, 35.0,
        ]),
        width: 200000.0,
        material: Color.RED.withAlpha(0.5)
    }}
/>
```
This gives the following error for the positions property: `Type 'Cartesian3[]' is not assignable to type 'Cartesian3 | Property | undefined'`. Clearly, the positions field should accept an array of positions(`Cartesian3[]`).

**Comment by rot1024** [comment]
Thank you for reporting. I will check it soon!

**Comment by rot1024** [comment]
https://github.com/CesiumGS/cesium/blob/main/Source/DataSources/CorridorGraphics.js#L14

This bug is caused by Cesium, because Resium just refers to type definitions of Cesium. It would be great to open a issue or send a pull request to Cesium.
