### ISSUE TITLE
How to enable fxaa in the view component or elsewhere

### ISSUE THREAD

**Issue by ruanhailiang** [reearth/resium#458]
How to enable fxaa in the view component or elsewhere, please help me.

**Comment by rot1024** [comment]
You can use Fxaa component:

```js
import { Viewer, Fxaa } from "resium";
```

```jsx
<Viewer>
  <Fxaa />
</Viewer>
```

**Comment by ruanhailiang** [comment]
Thank you for your reply.
Just using the above example will also cause this error:
DeveloperError: czm_FXAA has already been added to the collection or does not have a unique name.

**Comment by rot1024** [comment]
I don't know so much about how to use Fxaa. Resium just wraps Cesium, so that error may be due to usage of Cesium.

**Comment by ruanhailiang** [comment]
I found a way to turn it on for cesium:
```
viewer.scene.postProcessStages.fxaa.enabled = true
viewer.scene.fxaa = true
```
I tried to use it on resium:
```
<Viewer>
  <Scene fxaa={true} postProcessStages.fxaa.enabled = {true}>
  </Scene>
</Viewer>
```
but,postProcessStages.fxaa.enabled = {true} is not allowed. 
I have a brief look at the source code. I'm not sure. It seems that scene does not support the "postprocessstages" props.

**Comment by rot1024** [comment]
It seems a bug. I consider fixing fxaa.

Workaround:

```jsx
const ref = useRef(null);
useEffect(() => {
  const scene = ref.current?.cesiumElement?.viewer.scene;
  if (!scene) return;
  scene.postProcessStages.fxaa.enabled = true;
}, []);

// ...

<Viewer ref={ref}></Viewer>
```

**Comment by ruanhailiang** [comment]
thanks.
A method I have experimented with is also shared:
`const App = () => {
  let viewer: any; // This will be raw Cesium's Viewer object.
  useEffect(() => {
    viewer.scene.postProcessStages.fxaa.enabled = true;
  }, []);
  return (
    <Fragment>
      <Viewer
          ref={(e) => {
            entity = e && e.cesiumElement;
          }}
     />
      </Viewer>
    </Fragment>
}`

**Comment by rot1024** [comment]
I could not reproduce the bug. It works even when any props are specified to Fxaa component (FXAA was automatically enabled).

If the problem occurs again, reopen the PR.

- https://github.com/reearth/resium/blob/main/src/PostProcessStage/PostProcessStage.stories.tsx#L80
- https://resium.reearth.io/examples/?path=/story/postprocessstage--fxaa
