### ISSUE TITLE
Using Popper with Resium, getting error for anchorEl

### ISSUE THREAD

**Issue by BrinsterAman** [reearth/resium#460]
I am using Popper with Resium to populate an overlay. While using Resium's Entity component for my anchorEl I am getting following warning:
 Warning: Failed prop type: Material-UI: The `anchorEl` prop provided to the component is invalid.
It should be an HTML element instance or a referenceObject 
(https://popper.js.org/docs/v1/#referenceObject).
    in ForwardRef(Popper) (created by PopperPanel)
    in PopperPanel (created by AssetMapContainer)

Due to this, my popper is getting placed at top-left corner of my window.

**Comment by rot1024** [comment]
Resium components do not render any DOM expect Viewer and CesiumWidget. So they do not support popper at all. Calculate screen position from Cesium and use it to show popup.

**Comment by BrinsterAman** [comment]
@rot1024 I tried using window coordinates too, but it didn't work

**Comment by rot1024** [comment]
```jsx
import { SceneTransforms } from "cesium";

export default function Example() {
  const viewer = useRef(null);
  const [popperPosition, setPopperPosition] = useState();

  const mouseEvent = e => {
    if (!viewer.current?.cesiumElement) {
      return;
    }

    const scene = viewer.current.cesiumElement.scene;
    const picked = scene.pick(e.endPosition);
    const id = picked ? picked.id || picked.primitive.id : null;

    if (picked && id instanceof Entity) {
      const pos = SceneTransforms.wgs84ToWindowCoordinates(
        scene,
        id.position.getValue()
      );
      setPopperPosition({ x, y });
    }
  };

  return (
    <Viewer ref={viewer}>
      <Entity position={/* ... */} />
      {popperPosition && (
        <div style={{ position: "absolute", left: popperPosition.x, top: popperPosition.y }}>
          {/* ... */}
        </div>
      )}
    </Viewer>
  );
}
```
