### ISSUE TITLE
pathgraphics is not show

### ISSUE THREAD

**Issue by ilezflusss** [reearth/resium#461]
Hi, there

Resium version 1.13.1
Cesium version 1.76.0

![image](https://user-images.githubusercontent.com/62642909/103136202-6022cc80-46cf-11eb-9e48-ebdf6cb6baea.png)

We wrote the code above, but path graphics doesn't work. 
It has a very simple use but we could not understand why it is not.
We do not have any problems with the PointGraphics display. While points are updated position on the map, we do not find any representation related to the path.

**Comment by rot1024** [comment]
We have to use time-seriesed positions as position to display PathGraphcis: e.g. [TimeIntervalCollectionProperty](https://cesium.com/docs/cesiumjs-ref-doc/TimeIntervalCollectionProperty.html). It is due to Cesium API. Or consider using PolylineGraphics.
