### ISSUE TITLE
breakpoints is invalid when use vscode debug 

### ISSUE THREAD

**Issue by xueyida** [reearth/resium#478]
i use craco-cesium build the APP ,  edit with vscode ,then make a break point in the  APP ,  but the break point is invalid;
i guess the problem is the source-map,but can`t find the reson

**Comment by xueyida** [comment]
i deal this proble by delete **node_modules/resium/dist/*.map** file, i think can delete *.map files; in the production environment,these files is unuseful,and can`t debug by vscode or chrome debug tool;

**Comment by rot1024** [comment]
Do you mean Resium's source map is broken?

**Comment by xueyida** [comment]
> Do you mean Resium's source map is broken?

no, I dont think the source-map is broken;  I think Resium`s source map effect craco-cesium/webpack build  self app`s source-map; if the webpack or craco-cesium load the *.map, maybe   resium`s  source map broken;
when i delete resiume`s source-map in the /node_modules/resiume.... ,webpack or caro-cesium can build right source-map;u also  can use my way;  use chrome-devtools or vscode  test the source-map, if can make breakpoint in the source-map;

in fact,I dont find the reason, i just delete **node_modules/resium/dist/*.map file**, i can debug resiume`s souece-map,
can make a breakpoint in resium`s source-map with vscode; hope u can help me by location the problem , 

hahah.....

**Comment by rot1024** [comment]
Ok, there seems to be no problem with resium itself, so I'll close it. If the problem persists, please create an issue in the craco-cesium repository.
