### ISSUE TITLE
add trackedEntity to viewer

### ISSUE THREAD

**Issue by kmaynard616** [reearth/resium#479]
I am trying to implement https://sandcastle.cesium.com/?src=CZML%20Path.html&label=CZML In resium. I can get the line to draw but having trouble with the trackedEntity to follow the line. any help is appreciated.

thanks

**Comment by rot1024** [comment]
You can enable tracking for the entity with `track` prop in a Entity component: https://resium.darwineducation.com/components/Entity

**Comment by ianwalberg** [comment]
How do you set the zoom when tracking an entity?

**Comment by nt10307** [comment]
I'm also wondering how to allow the user to control the zoom on a tracked object.  In this example I found online (https://glitch.com/edit/#!/satellite-viewer), the user can still zoom while tracking an object, but I haven't been able to replicate that with resium.  Anyone figure that out?

**Comment by rot1024** [comment]
Refer to #496
