### ISSUE TITLE
Real time CZML 

### ISSUE THREAD

**Issue by kmaynard616** [reearth/resium#480]
I am trying to process real time CZML and append it to the current CzmlDataSource (using web sockets). I can create new ones but I can not append to the existing data source. I tried to call process on the CzmlDataSource but I get process is not a function. see below 

const viewer = this.ref.current.cesiumElement
if(this.state.count==0){
viewer.dataSoures.add(Cesium.CzmlDataSorce.load(data)
} else{
viewer.dataSources.getByName("name").process(response);
}

**Comment by rot1024** [comment]
This question is not related to Resium. It's a matter of usage of Cesium.

I found a typo: dataSoures
