### ISSUE TITLE
computeViewRectangle is wrong

### ISSUE THREAD

**Issue by nhatnkv** [reearth/resium#483]
I use viewer.camera.computeViewRectangle for get bounding box coordinates. But I got a errors 'TypeError: Cannot read property 'west' of undefined' when I drag to outside the map.

<img width="528" alt="Screen Shot 2021-03-25 at 18 33 04" src="https://user-images.githubusercontent.com/20665025/112467810-157e2280-8d9a-11eb-967d-31e7813c794c.png">

I follow this example https://sandcastle.cesium.com/?src=Hello%20World.html&label=Showcases&gist=22dd300be2923f7069b144976ddf8ef5

How I can fix it? thanks

**Comment by rot1024** [comment]
Your question is not related to resium.
