### ISSUE TITLE
ScreenSpaceEventHandler action type is incomplete

### ISSUE THREAD

**Issue by Hugo-Hache** [reearth/resium#484]
When implementing a handler for the ScreenSpaceEventType.MOUSE_MOVE, I faced an issue where the position returned in my action had no  property `position`, but a `startPosition` and `endPosition`. 

I checked the [Cesium source code](https://github.com/CesiumGS/cesium/blob/ab07bcb130d99baaae08ce5e4346ae79899136e0/Apps/Sandcastle/gallery/development/Picking.html#L66) and it seems to be the expected behavior.
I suppose `event` properties might differ according to the EventType concerned.

To circumvent this issue I currently declare my action with event as any:

```
const myAction = (event: any) => { event.endPosition... }

...

<ScreenSpaceEventHandler useDefault>
  <ScreenSpaceEvent type={ScreenSpaceEventType.MOUSE_MOVE} action={myAction} />
</ScreenSpaceEventHandler>
```

If I submit a PR with a type `(e: { position: Cartesian2; } | { startPosition: Cartesian2; endPosition: Cartesian2;} ) => void` would it be a good solution for you?

Versions used:
- Resium 1.13.1
- Cesium 1.80.0

**Comment by rot1024** [comment]
Thank you! Yes, your PR will solve this issue! Please feel free to open PRs.
