### ISSUE TITLE
Add ability to have onClick (and other) handlers work when modifier keys are held

### ISSUE THREAD

**Issue by smilligan93** [reearth/resium#488]
Hello,

I was wondering if it's possible to have the onClick/onMouseOver/onRightClick/etc on the Components also be called when the shift key/alt key/ctrl key are held down? Looking through the code, I think it could be done in the EventManager where the setInputAction is registered, possibly by registering all the modifier keys as well. We are trying to support shift-clicking entities to allow multiple selected and having this functionality would benefit us greatly. 

Thanks for all the work you do!

**Comment by rot1024** [comment]
This can be done using the ScreenSpaceEventHandler component.
