### ISSUE TITLE
How to set state onTick

### ISSUE THREAD

**Issue by hatched-esther** [reearth/resium#489]
Hello :D 
I'm trying to set a state in an onTick event for a clock. 

```
   <Clock
        startTime={start.clone()}
        stopTime={stop.clone()}
        currentTime={start.clone()}
        multiplier={50}
        onTick={_.throttle(handleHeadingValue, 1000)}
      />
```

Here is the `handleHeadingValue` function. 

```
  const handleHeadingValue = (clock) => {
//setting the state here
  setHeadingValue({
        heading: ref.current.cesiumElement._properties._heading.getValue(
         clock.currentTime
         ),
       });
    }
  };
```

The problem is that for some reason doing this the Cesium Viewer goes crazy and it looks like it tries to re-render over and over which freezes the app. 
May I have some insight as to what Im doing wrong? 

thank you!!

**Comment by hatched-esther** [comment]
Any help here please? Here is a code sandbox showing my problem: https://codesandbox.io/s/resium-cesium-context-forked-bpjuw?file=/src/ViewerComponent.js

**Comment by rot1024** [comment]
`JSON.parse(...)` is too heavy to exec every render time. Minimize the amount of processing during rendering.

I won't go into too much depth here, as this is a basic matter of React.
