### ISSUE TITLE
too many WMS Queries while rendering.

### ISSUE THREAD

**Issue by peerusman** [reearth/resium#494]
Hi,
I am building a generic React Map using Resium with Geoserver, I have many WMS layers which I would like to render on resium. 
my current code is very simple just grab the URL and layer names from rest API and try to render, 

`{mapLayers.map(layer => {
          return (
            <ImageryLayer
              key={layer.name}
              alpha={0.6}
              imageryProvider={new WebMapServiceImageryProvider(layer)}
            />
          )
        })}`

`useEffect(() => {
    if (map.id) {
      const mapLayers = (map.layers || []).map((layer = {}) => {
        return {
          url: (layer.mapServer || {}).url,
          layers: layer.name,
          parameters: {
            format: 'image/png',
            transparent: 'true',
          },
        }
      })
      setMapLayers(mapLayers)
    }
  }, [map])`
I am using only 1 wms layer to test it.
Now if I run this simple code the network request to fetch the wms images are huge around 83 calls when just change 1 zoom level
![image](https://user-images.githubusercontent.com/20946339/118950231-0e732b00-b96b-11eb-80fc-69a2551dd8d1.png)

But the case code in cesium sandcastle  7 request only
https://sandcastle.cesium.com/?src=Web%20Map%20Service%20(WMS).html&label=All
![image](https://user-images.githubusercontent.com/20946339/118950714-82153800-b96b-11eb-9df7-effbc6c8173c.png)

Please help me in this regard because it is not usable if we have like 5 to 7 layers it keep loading till it gets all the request finished.

**Comment by rot1024** [comment]
`{mapLayers.map(layer => { return ( <ImageryLayer key={layer.name} alpha={0.6} imageryProvider={new WebMapServiceImageryProvider(layer)} /> ) })}`

This code may create difference components every render time. So you have to separate this components, using `React.memo` for the component, or using use `useMemo` for `mapLayers` to prevent re-rendering without prop change.
