### ISSUE TITLE
CopyWebpackPlugin not work

### ISSUE THREAD

**Issue by shiftonetothree** [reearth/resium#495]
In this doc https://resium.darwineducation.com/installation1#3-add-copy-webpack-plugin not work,
this work:
`new CopyWebpackPlugin([
    {
      from: 'node_modules/cesium/Build/Cesium', 
      to: 'cesium'
    },
  ])`
ref 
https://github.com/webpack-contrib/copy-webpack-plugin/issues/455

**Comment by rot1024** [comment]
Yes, option of CopyWebpackPlugin has been changed. I'll update it soon!
