### ISSUE TITLE
How to load kml file on cesium resium react components / Documentation method is not working

### ISSUE THREAD

**Issue by ardilan** [reearth/resium#497]
I need to load a kml file on react component using resium-cesium. I have followed the exact procedure as shown in the official resium page as follows.

https://resium.darwineducation.com/getting_started#loading-your-own-data

I tried to load sample kml file from official github page of cesium. https://github.com/CesiumGS/cesium/tree/master/Apps/SampleData I have downloaded this sampleData folder and put under the src folder of react project. Then tried to load as follows.

```
import React from "react";
import { Viewer, KmlDataSource, GeoJsonDataSource } from "resium";

const data = {
  type: 'Feature',
  properties: {
    name: 'Coors Field',
    amenity: 'Baseball Stadium',
    popupContent: 'This is where the Rockies play!'
  },
  geometry: {
    type: 'Point',
    coordinates: [-104.99404, 39.75621]
  }
};

const App = () => (

  <Viewer full>
    <KmlDataSource data={"src/SampleData/kml/facilities/facilities.kml"} />
    <GeoJsonDataSource data={data} />
  </Viewer>

);

export default hot(App);
```

I should receive a similar result of this. https://sandcastle.cesium.com/index.html?src=KML.html But I did not receive. 

you can check the issue in stackoverflow using following link.
https://stackoverflow.com/questions/67880413/how-to-load-kml-file-on-cesium-resium-react-components

Thank you

**Comment by rot1024** [comment]
This is a basic question in React development. 

```
<KmlDataSource data={"src/SampleData/kml/facilities/facilities.kml"} />
```

There is a mistake here: create-reeact-app is running on the webpack server, so local files are not delivered. Please put the KML in a public directory if you need it. For more information, please refer to this page: https://create-react-app.dev/docs/using-the-public-folder/

**Comment by ardilan** [comment]
I am really sorry for asking very basic question. That is worked.... Thank you very much
