### ISSUE TITLE
useState(), useEffect() hook causes Viewer/ImageryLayer reload 

### ISSUE THREAD

**Issue by vlkpa** [reearth/resium#498]
When my component with Resium Viewer is changed with useState()/useEffect() hooks map is re-rendered. Maybe same problem as [here](https://github.com/reearth/resium/issues/372#issuecomment-649772866)

**Comment by rot1024** [comment]
That is the expected behavior; please make good use of useMemo and other methods to prevent the read-only property from changing.

See also: #372
