### ISSUE TITLE
Showing 3D model using `Model` Component

### ISSUE THREAD

**Issue by MosheG23** [reearth/resium#501]
Hi!

I'm trying to add 3d object to my project (code submitted at the end), I tried to use the example from the docs and I'm getting type error:
**TypeError: Cannot set property '_cacheKey' of undefined**

Even when I'm trying to ModelGraphics inside an Entity i"m getting other error:
**TypeError: Cannot set property '_definitionChanged' of undefined**

Codes:
(modal_3D is an array of glb/gltf objects that imported)

Model Code:
(import actions from @storybook/addon-actions, gets same error with and without)
<Model
          url={modals_3D[0]}
          modelMatrix={modelMatrix}
          minimumPixelSize={128}
          maximumScale={20000}
          onReady={action("onReady")}
          onClick={action("onClick")}
/>

ModelGraphics:
<Entity name="modal" model={{ url: modals_3D[0]} } position={pos}>
{(!(_.isEmpty(modal3D))) ?  <ModelGraphics minimumPixelSize={128} modelMatrix={modal3D.modelMatrix} uri={modal3D.url} maximumScale={20000} orientation={orientation} />  : <> </>}
</Entity>

The project is amazing and highly helpful thanks for the great work.

**Comment by MrShtrahman** [comment]
Hi, perhaps try to define your model as so:
```
<Entity name="modal" model={{ url: modals_3D[0]} } position={pos}>
   <ModelGraphics
   url={modals_3D[0]}
   modelMatrix={modelMatrix}
   minimumPixelSize={128}
   maximumScale={20000}
   onReady={action("onReady")}
   onClick={action("onClick")}
   />
</Entity>
```
