### ISSUE TITLE
How to load KML/KMZ data files externally

### ISSUE THREAD

**Issue by ardilan** [reearth/resium#502]
Hi, Thank you for your awesome work...
I need to load kml files which are downloaded from server dynamically. Which means I need to load kml files in run time. 

as an example, client app receive some kml data file from server through an API call, then I need to show that KML/KMZ file data into the resium world map. So I need to load kml files externally. I tried some codes but it does not work. Could you please check my code and let me know how to load KML or KMZ files out side of <viewer></viewer>

````
import './App.css';
import { hot } from "react-hot-loader/root";

import React, { createRef } from "react";
import { Viewer, KmlDataSource} from "resium";


class App extends React.Component {

  constructor(props) {
    super(props);
    this.ref = createRef();
  }

  loadKmlFileExternal() {
    if (this.ref.current && this.ref.current.cesiumElement) {
       //I tried two code syntax but no lucky. 
      <this.ref.current.cesiumElement>
        <KmlDataSource data={process.env.PUBLIC_URL + "/kml/gdpPerCapita2008.kmz"} />;
      </this.ref.current.cesiumElement>
      //or
      this.ref.current.cesiumElement.dataSources.add(KmlDataSource.load(process.env.PUBLIC_URL + "/kml/gdpPerCapita2008.kmz"));
    }
  }


  render() {
    let content = null;

    content = (
      <Viewer full ref={this.ref} >
        <KmlDataSource data={process.env.PUBLIC_URL + "/kml/facilities/facilities.kml"} /> // This works, but I need to load outside from Viewer
      </Viewer>
    );

    return (      
      <div>
        {content}
        {this.loadKmlFileExternal()}
      </div>
    );
  }
}

export default `hot(App);
```

**Comment by rot1024** [comment]
Familiarize yourself with the basics of React, especially how to use ref's. Use ref's to get Cesium objects and manipulate them in your methods. You can also refer to this document.

- https://reactjs.org/docs/refs-and-the-dom.html
- https://resium.reearth.io/guide#accessing-to-a-raw-cesiums-element
