### ISSUE TITLE
Missing example documentation 

### ISSUE THREAD

**Issue by chriswalz-bg** [reearth/resium#504]
Hi thank you for all your work developing Resium. It's super helpful. 

I don't see any examples / these links don't appear to work. 

https://resium.darwineducation.com/examples/?path=/story/pointprimitivecollection--basic

https://resium.darwineducation.com/examples/?path=/story/polylinecollection--basic

`pointprimitivecollection` and `polylinecollection` would be very helpful since I need to draw a large number of lines and points (thousands)

**Comment by rot1024** [comment]
Not all examples are currently covered. Pull requests are welcome!
