### ISSUE TITLE
How to call/read terrain data in Resium from terrain data that we uploaded on CesiumIon?

### ISSUE THREAD

**Issue by saharilarshad** [reearth/resium#505]

**Comment by rot1024** [comment]
You might want [sampleTerrain](https://cesium.com/learn/cesiumjs/ref-doc/sampleTerrain.html)?

**Comment by saharilarshad** [comment]
Thanks.. its work for me..

One more thing.. how can i do to apply this function "flyToBoundingSphere" in React/Resium?
I do have a set of 3D Tiles data. So when I click, it will fly to the layer..

appreciate if u can help me
