### ISSUE TITLE
while using useCesium hook viewer or scene is always undefined

### ISSUE THREAD

**Issue by Manisharote** [reearth/resium#508]
Hi, 

While using "const {viewer , scene}  = useCesium()" hook to get the reference for viewer and scene , both are always undefined irrespective I use in same component where I am creating <Viewer/> component or getting reference of viewer in any other components. 

`import React, { useEffect, useState, useRef } from "react";
import {  Viewer,  GeoJsonDataSource,  CameraFlyTo,  useCesium,  Scene,} from "resium";
import {  Color,  Cartesian3} from "cesium";
import lot from "../Data/Lot_WGS.json";

const MapViewer = () => {
const { viewer, scene,  } = useCesium(); // the viewer and scene always undefine

  useEffect(() => {
    if (viewer) { //  The viewer is always undefined. 
//If viewer do some thing with viewer --
}
}, [viewer])

 return (
    <Viewer
   
      full
      fullscreenButton={true}
      id={"mapViewer"}
      infoBox={false}
      timeline={false}
      animation={false}>
  {lot && (
        <GeoJsonDataSource
          data={lot}
       
          fill={new Color(0, 0, 0, 0.0)}
          stroke={Color.WHITE}
          strokeWidth={3}  ></GeoJsonDataSource>)}

  </Viewer>
};

export default MapViewer;

`

I am using cesium 1.85.0 and resium 1.13.1

**Comment by rot1024** [comment]
useCesium hooks can be used only at components inside Viewer. [Use ref](https://resium.reearth.io/guide#accessing-to-a-raw-cesiums-element) to access the Viewer object.

**Comment by Manisharote** [comment]
Noted, thanks
