### ISSUE TITLE
EntityDescription does not render on first click.

### ISSUE THREAD

**Issue by nickgrealy** [reearth/resium#512]
> v1.13.1 has been released. Please try it and reopen this issue if the issue persists.

_Originally posted by @rot1024 in https://github.com/reearth/resium/issues/436#issuecomment-701140692_

Looks like this is still an issue (regressed?).

I've just come across this issue in `"resium": "1.14.2"`. The first `EntityDescription` object I click on, does not show the description. 

Then second Entity I click on shows the EntityDescription. I click back on the first Entity, and now it show the EntityDescription.

This is a fresh ReactJS project - happy to share source (if required).

package.json
```json
"dependencies": {
    "@craco/craco": "6.3.0",
    "@hot-loader/react-dom": "17.0.1",
    "@testing-library/jest-dom": "5.14.1",
    "@testing-library/react": "12.1.0",
    "@testing-library/user-event": "13.2.1",
    "@types/jest": "27.0.1",
    "@types/node": "16.9.1",
    "@types/react": "17.0.20",
    "@types/react-dom": "17.0.9",
    "@types/react-router-dom": "5.1.8",
    "cesium": "1.85.0",
    "craco-cesium": "1.2.0",
    "craco-plugin-react-hot-reload": "0.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-hot-loader": "4.13.0",
    "react-router-dom": "5.3.0",
    "react-scripts": "4.0.3",
    "resium": "1.14.2",
    "typescript": "4.4.3",
    "web-vitals": "2.1.0"
  }
```

**Comment by zblcool** [comment]
Reproduced and find the same issue. 
After digging a little bit I find the reason for this issue but haven't found a perfect solution yet
##  The reason 
> The reason is that the EntityDescription component did not handle the removal of ` cssium-infoBox-bodyless` class correctly. and together with the `height` of the iframe as indicated in the pic below. 
![Screen Shot 2021-09-24 at 3 18 36 pm](https://user-images.githubusercontent.com/9151815/134622466-6e87fd2b-b876-4c34-8aee-8fc5e204da7b.png)
## Current Solution
To solve this issue. you can try to correct these two things. 

## potential source of the issue
In `resium/src/EntityDescription/EntityDescription.ts ` The snippet below was actually trying to handle this but not sure why it's not working right now for the first click.
> ![Screen Shot 2021-09-24 at 3 19 59 pm](https://user-images.githubusercontent.com/9151815/134622851-35990c25-9bfd-4191-a2e0-15607ca05772.png)

Pls check if possible

Ash

**Comment by rot1024** [comment]
Thank you.

It would be great if someone creates a pull request!

**Comment by rot1024** [comment]
v1.14.3 released!
