### ISSUE TITLE
Orientation does not work on entity(ies).

### ISSUE THREAD

**Issue by CLBID** [reearth/resium#523]
In cesium, you can change the orientation of an entity.  Resium imports the orientation, but nothing works re the orientation.  Unable to make any orientational changes to the entity.  I have tried multiple options.

**Comment by CLBID** [comment]
This is a bug

**Comment by CLBID** [comment]
Anyone have any update on when the orientation will be fixed.   We definitely need a way to change the orientation of an ellipsoid.

**Comment by rot1024** [comment]
Please provide sample codes which reproduces the problem. Also test it without Resium and confirm it works.

**Comment by rot1024** [comment]
Closed due to no reply. Let me know if you have any more problems.
