### ISSUE TITLE
Issue with tiles stretching while rendering

### ISSUE THREAD

**Issue by daltonrussell** [reearth/resium#526]
I am running into an issue when I try and view the map in a resium viewer, the tiles are stretching and I cannot figure out how to resolve this. 
![Map Tearing](https://user-images.githubusercontent.com/6609047/142049132-cc00cff5-a027-44ff-b51d-8703930941c6.PNG)

I have checked to ensure the images are being served correctly and when looking in the resources, they appear normal, it is doing the stretching when it is being rendered in the container. 

This is the code used to render from the locally hosted WMS server.: 

![CodeSnippet](https://user-images.githubusercontent.com/6609047/142049388-e3f061cd-c43b-4f73-9e40-193a87039677.PNG)

**Comment by rot1024** [comment]
That issue is not due to Resium. Discuss about it at [Cesium Community](https://community.cesium.com/)
