### ISSUE TITLE
Run   "postinstall": "symlink-dir node_modules/cesium/Build/Cesium public/cesium" Issue on Vercel

### ISSUE THREAD

**Issue by zeta-o** [reearth/resium#529]
Hi guys. I'm having an issue running resium in Vercel.

The build process fails on the server with the following error:

Failed to process build result for "cesium". Data: {"type":"FileFsRef"}.
--
12:07:09.905 | [Error: EISDIR: illegal operation on a directory, read] {
12:07:09.905 | errno: -21,
12:07:09.905 | code: 'EISDIR',
12:07:09.905 | syscall: 'read'
12:07:09.905 | }

It is happening in the Vercel instance but not in my local env. 

I'm using:
"next": "12.0.3",
"react": "17.0.2",
"resium": "^1.14.3"

Someone else faced this problem before?
Thanks in advance.

**Comment by rot1024** [comment]
Vercel is a serverless service, so symlink may not work for some reasons.

Did you try just copying files?

```
"postinstall": "cp -r node_modules/cesium/Build/Cesium public/cesium"
```

**Comment by zeta-o** [comment]
@rot1024 Thank you very much! It works.
