### ISSUE TITLE
rotateRight() function

### ISSUE THREAD

**Issue by luighis** [reearth/resium#530]
Hi Guys, I was looking for the function rotateRight(), which exists in cesium documentation ( https://acortar.link/HpEMUY ), but I didn’t find any implementation in resium. Any guide how is the right way to implement this functionality.

Thanks in advance.

**Comment by rot1024** [comment]
Use ref to access a raw Camera object: https://resium.reearth.io/guide#accessing-to-a-raw-cesium-element

```jsx
const ref = useRef(null);

return (
  <Viewer ref={ref}>
    <Clock onTick={() => ref.current?.camera.rotateRight(0.005)} />
  </Vieweer>
);

```

**Comment by luighis** [comment]
Hello, I need to add this to make it work: 
```
<Clock
    onTick={() => ref.current?.cesiumElement?.camera.rotateRight(0.002)}
/>
```
Greetings and thanks for the help
