### ISSUE TITLE
How adjust the camera zoom to the current size screen

### ISSUE THREAD

**Issue by luighis** [reearth/resium#531]
Hello.
would there be a way to make the globe occupy the entire height when starting the app and then adjust to the width in mobile mode.
I'm using moveForward, zoomIn but can't set it to fit.
if you can give me an idea please. Thanks
![Captura de pantalla 2021-12-16 111449](https://user-images.githubusercontent.com/41096968/146388628-a70a6301-5f44-4c88-a006-89620692595b.jpg)
![Captura de pantalla 2021-12-16 111616](https://user-images.githubusercontent.com/41096968/146388647-de57bf03-3c54-4a7d-862e-7a291bb50bcd.jpg)

**Comment by rot1024** [comment]
This issue is not related to Resium. Please discuss about it at [Cesium Community](https://community.cesium.com/)
