### ISSUE TITLE
Get Current Position

### ISSUE THREAD

**Issue by rustamhasymov** [reearth/resium#536]
Hello I need help, I built a component in which entity gets a set of coordinates and my plane flies in a circle at these points, tell me how do I get the current position of the plane from these coordinates, thank you

**Comment by rot1024** [comment]
Note: this question is not related to Resium. Use [Cesium Community](https://community.cesium.com/)

What is position: screen position or cartographic position?

- Screen position -> Cartographic position: https://github.com/reearth/resium/issues/219
- Cartographic position -> Screen position: https://cesium.com/learn/cesiumjs/ref-doc/SceneTransforms.html#.wgs84ToWindowCoordinates
