### ISSUE TITLE
Drag and Drop czml files inside on Viewer

### ISSUE THREAD

**Issue by rustam-gasymov** [reearth/resium#539]
Can somebody to give example how to build drag and drop elements inside on viewer

**Comment by HideBa** [comment]
@rustam-gasymov We also have another library [cesium-dnd](https://github.com/reearth/cesium-dnd) which allows you to drag and drop cesium's entity.

**Comment by rustam-gasymov** [comment]
we can use this library with resium?

**Comment by HideBa** [comment]
@rustam-gasymov 
resium is the library that allows us to handle cesium as we use React. 
Of course, you can use this with resium as well. 
[here](https://github.com/reearth/reearth-web/blob/a90dda4906004dbbacbeaabb93c043efc8655daf/src/components/molecules/Visualizer/Engine/Cesium/hooks.ts#L261) is our example how we use it.
