### ISSUE TITLE
Using resium offline

### ISSUE THREAD

**Issue by jabusir** [reearth/resium#540]
Is there anyway to use Resium offline? I notice in the network tab there are various dependencies that are coming from external sources. 

How would I go about leveraging these resources in an offline setting?

Thanks

**Comment by rot1024** [comment]
Whether an application can be used offline or not is not a Resium issue, but a build tool configuration issue: if you load React or other software from a CDN, it will not work offline, and if you build it including React and distribute the build results properly, it may work offline. If you build with React and distribute the build result properly, it may work offline.
