### ISSUE TITLE
RuntimeError: The Resource is already being fetched

### ISSUE THREAD

**Issue by dabuchera** [reearth/resium#544]
Getting this error while trying to using Cesium3DTileset
Code below

```
function App() {

    const handleReady = tileset => {
      if (viewer) {
        viewer.zoomTo(tileset);
      }
    };

    return (
      <Viewer
        full
        ref={e => {
          viewer = e && e.cesiumElement;
        }}>
        <Cesium3DTileset url={IonResource.fromAssetId(5714)} onReady={handleReady} />
      </Viewer>
    );}
```

**Comment by dabuchera** [comment]
Solved

**Comment by z-mach9** [comment]
I'm also facing this issue.  How did you resolve this?

It seems to be linked to React 18's new Strict Mode behavior of unmounting and remounting components during development.

**Comment by avakin** [comment]
For dependencies
```typescript
 "react": "^18.2.0",
 "react-dom": "^18.2.0",
 "cesium": "^1.105.2",
 "resium": "^1.16.1",
``` 

You can just remove `React.StrictMode` into `src/index.tsx` file. This wrapping causes the 

`RuntimeError: The Resource is already being fetched`

Instead of this: 

```typescript

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
``` 
just left this

```typescript
root.render(<App />);
``` 
The issue was facing only in dev build. For productions there were any issues.
