### ISSUE TITLE
Unable to access Map Rotation Functionality on 2D Maps

### ISSUE THREAD

**Issue by utkarsh447** [reearth/resium#547]
Hi all, 
I am using Cesium `v1.93.0` along with Resium `v1.14.3` on React 16.8. I want to include the basic action of middle-click or ctrl + left click functionality for map rotation on 2D Maps.
I am currently using my Viewer as follows:
```
<Viewer style={{height: "80vh"}} timeline={false} geocoder={false} 
vrButton={false} animation={false} scene3DOnly={false} sceneModePicker={false}
ref={(e) => { window.viewer = this.viewer = e && e.cesiumElement; }} 
fullscreenButton={false} sceneMode={SceneMode.SCENE2D}}>
{/* Some Body Content */}
</Viewer>
```
Here, no action for map rotation is being triggered 

I have referred to this example https://stackoverflow.com/a/35858166 and tried to migrate the same functionality from Cesium to Resium, but I am failing on that.

I have also referred to storybook examples by resium but there also no example of map rotation is given.

I would greatly appreciate it if you can provide a guide to implementing 2D map rotation using Resium in ReactJs.

**Comment by rot1024** [comment]
You may have to set `MapMode2D` to `Scene` also, but current Resium ignores unknown props. I will fix it and release a new version.

**Comment by rot1024** [comment]
New version v1.15 has been released and you can set `mapMode2D` prop to Scene component.

**Comment by utkarsh447** [comment]
Thank you @rot1024 . I greatly appreciate such quick response and patch on the requested enhancement!
