### ISSUE TITLE
resium issue in npm

### ISSUE THREAD

**Issue by NoorAhmd** [reearth/resium#549]
At the moment you can not install resium package with npm.

$ npm i resium
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "resium" under a package
npm ERR! also called "resium". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bothx\AppData\Roaming\npm-cache\_logs\2022-06-30T11_25_45_289Z-debug.log

**Comment by rot1024** [comment]
I could not reproduce that problem in my environment. It's probably an environment-specific issue such as networking or caching. Try clearing your cache and using the latest version of Node.js and npm.
