### ISSUE TITLE
Cesium navigation controls.

### ISSUE THREAD

**Issue by vaibhav135** [reearth/resium#550]
Hi, I would like to know if there is any support for cesium navigation controls as shown in the picture below.

![image](https://user-images.githubusercontent.com/39329182/176843401-975d6dc6-1e9b-43a0-929b-bbca3e5106ed.png)

Although I was able to get the navigation controls with the [cesium-navigation-es6](https://www.npmjs.com/package/cesium-navigation-es6) library. But the reset doesn't seem to be working, and also the `defaultResetView` has type `Rectangle` only.
I also checked the same for cesium-community but their solutions don't work for me. 

[cesium-community-post](https://community.cesium.com/t/how-to-add-navigation-controls/13448)
[google-groups-post](https://groups.google.com/g/cesium-dev/c/AAO0y7sNEaU)
[cesium-navigation-es6 library](https://github.com/richard1015/cesium-navigation-es6)
[cesium-navigation npm library](https://github.com/nmccready/cesium-navigation)

**Comment by rot1024** [comment]
Study up on React and https://resium.reearth.io/guide#accessing-to-a-raw-cesium-element, you can accomplish this with a combination of useRef and useEffect.

```js
import CesiumNavigation from "cesium-navigation-es6";

export function Component() {
  const ref = useRef(null);
  const navigator = useRef();
  useEffect(() => {
    if (ref.current) {
      navigator.current = new CesiumNavigation(ref.current.cesiumElement, { /* options */ });
    }
  }, []);

  return <Viewer ref={ref} />;
};
```

**Comment by vaibhav135** [comment]
Hii,
I think I already mentioned that I was able to get the navigation (which is obviously with the use of useRef and useEffect) my question was not how I can get the navigation controls (that I am already familiar with how) my question is how I can make the reset button work. Because It's not working.
P.S. Please do not close an issue without asking.

**Comment by rot1024** [comment]
Sorry, I did not read it carefully.

Perhaps there is a problem with the implementation of cesium-navigator-es6. It is unlikely that Resium is involved in that problem. This is because cesium-navigator-es6 can be used in the same way when using Cesium directly without Resium. Resium is a thin wrapper and should not interfere with cesium-navigator-es6.

**Comment by vaibhav135** [comment]
Then is there any solution to this problem as of now? Since a lot of the comments in the library is in mandarin it was hard to translate and understand things at the same time. Please let me know if I could be of any help in any ways.
