### ISSUE TITLE
Facing the same access token issue as #60

### ISSUE THREAD

**Issue by prinzz1208** [reearth/resium#551]
Unable to update default access token. Even tried adding `Ion.defaultAccessToken = "XXXX"` before ReactDOM.render(). Still facing the same default access token issue. Plz, help. Referenced Issue https://github.com/reearth/resium/issues/60

**Comment by prinzz1208** [comment]
Currently, the default access token is also failing due to the deprecation of the npm cesium module version. Updating the npm cesium module version starts to work but is not a permanent solution. I want to pass my access token to it at the initialization of the Viewer component.

**Comment by rot1024** [comment]
Note: This issue is not due to Resium. Resium does not handle any Cesium Ion access tokens.

For example, ImageryProvider should be re-created after setting Cesium Ion access tokens:

```js
// instead of createWorldImagery
const provider = new IonImageryProvider({
  assetId: IonWorldImageryStyle.AERIAL,
  accessToken: Ion.defaultAccessToken,
})
```
