### ISSUE TITLE
examples don't work for the components 

### ISSUE THREAD

**Issue by deven-gqc** [reearth/resium#556]
Upon clicking on the example of Cesium3DTileset, it redirects to [this site](https://resium.reearth.io/examples/?path=/story/cesium3dtileset--basic%22) on the resium website,
![image](https://user-images.githubusercontent.com/86305049/183755898-efd370c9-c037-4309-bd48-00e0a0a25bec.png)

No examples on the site seem to show up
![image](https://user-images.githubusercontent.com/86305049/183755815-d7a96ea9-4ee9-4bf0-a9ee-937295038bc1.png)

**Comment by deven-gqc** [comment]
cc @jacobgqc

**Comment by rot1024** [comment]
👉 https://resium.reearth.io/examples/?path=/story/cesium3dtileset--basic

Some links in docs are wrongly linked. All API documentation is auto-generated, so modifying links requires modifying scripts, source code comments, etc. PR is welcome.
