### ISSUE TITLE
SyntaxError: The requested module '/node_modules/mersenne-twister/src/mersenne-twister.js?v=af747562' does not provide an export named 'default'

### ISSUE THREAD

**Issue by Wecle** [reearth/resium#557]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/66044182/185065361-573f9c70-2a5b-4267-b4a2-a942a6559fe1.png">

node v14.15.5

I copy the same code from example/vite.Running successful but work error.

**Comment by rot1024** [comment]
Cesium has recently redesigned its dependent libraries, but Vite currently has a bug that prevents it from building CommonJS properly, which seems to be causing build errors. I am waiting for Vite to be fixed that bug.

Check: https://github.com/vitejs/vite/issues/3910

**Comment by Wecle** [comment]
> Cesium has recently renewed its dependent libraries, but Vite currently has a bug that prevents it from building CommonJS properly, which seems to be causing build errors. I am waiting for Vite to be fixed that bug.
> 
> workaround: downgrade Cesium to v1.95
> 
> Check: [vitejs/vite#3910](https://github.com/vitejs/vite/issues/3910)

Thanks a lot!Its working now.

**Comment by rot1024** [comment]
@Wecle https://github.com/nshen/vite-plugin-cesium/issues/34 was a PR we should reference to. The issue has been solved!
