### ISSUE TITLE
Model creation bug

### ISSUE THREAD

**Issue by bigkrp** [reearth/resium#559]
We miss `scene` property [when create](https://github.com/reearth/resium/blob/30f276454a04abfd0cc869525ce07840978e3dc2/src/Model/Model.ts#L80) `Model` via `fromGltf` method. As result we got `DeveloperError` for `heightReference`:

```Height reference is not supported without a scene and globe.```

![Screenshot from 2022-08-29 10-26-05](https://user-images.githubusercontent.com/11586744/187146906-dac39ce4-f7ca-4e84-9273-e087a722a825.png)

**Comment by rot1024** [comment]
Thanks. Fixed and v1.15.1 has been released!
