### ISSUE TITLE
Upgrading to Resium ^1.15 causes build errors

### ISSUE THREAD

**Issue by MatthewHerbst** [reearth/resium#564]
Resium `1.14.3` works great, however, upon upgrading to `1.15.0` or `1.15.1` we encounter build errors. Specifically, `Module not found` errors when Webpack (`v4.46.0`) is building the files.

I'm assuming this has something to do with the switch to Vite, though I'm not familiar enough with Vite to spot the issue.

**Comment by rot1024** [comment]
See examples directory in this repo, webpack does not seem to be causing any errors.

**Comment by Nikitak211** [comment]
Hi there I am running in the same issue in 1.15.1 
I am using the original files , do yarn and non run build
But it’s fails to build due some error
![59BCA8AF-1E9B-446C-8ACA-2C2F3C367A9B](https://user-images.githubusercontent.com/86636988/230744294-b787fc4a-98b3-4aba-b95d-a582e2f02b14.jpeg)
