### ISSUE TITLE
404 on every asset - Vite

### ISSUE THREAD

**Issue by RZalmon** [reearth/resium#575]
Hi. Im using Resium in Vite, Unfortunately I'm getting 404 for every asset(.css\ png\ jpg)-

React: 18.0.0
Vite: 4.0.4
Resium: 1.16.0
Cesium: 1.101.0
vite-plugin-cesium: 1.2.22
@vitejs/plugin-react: 2.0.0

e.x-
http://localhost:3003/cesium/Widgets/Images/ImageryProviders/sentinel-2.png

![resium error](https://user-images.githubusercontent.com/60194209/213922587-5b8215a9-3b0c-4e0b-ae6f-8bd679159251.png)

![image](https://user-images.githubusercontent.com/60194209/213987637-25f5470d-119a-4abe-be82-ae0747367b70.png)

**Comment by rot1024** [comment]
It's not related to Resium.
