### ISSUE TITLE
Unable to Import Entity From 3rd Party npm Package

### ISSUE THREAD

**Issue by reggie3-braingu** [reearth/resium#578]
I have an npm package that exports multiple Resium `Entity` components.  However, when importing the entities into a Resium `Viewer` component those entities are not rendered.

The package exports the following component:

```javascript
import { Cartesian3, Viewer as CesiumViewer } from "cesium";
import { BillboardGraphics, Entity } from "resium";

const TestEntity = ({ viewer }: { viewer: CesiumViewer }) => {
  return (
    <>
      <Entity
        description="test"
        name="Key West"
        point={{ pixelSize: 10 }}
        position={Cartesian3.fromDegrees(-81.7842, 24.5554, 100)}
       // adding this does not work either, though it does provide the Viewer as a Context
      >
        <BillboardGraphics pixelSize={10} />
      </Entity>
    </>
  );
};
```

I think it is because the entity isn't getting a valid context because adding these `console.log`s in the `Entity.tsx` file in the `resium` library:

![image](https://user-images.githubusercontent.com/90011823/218113579-fdfa245d-5cec-41ed-8fb4-cc53fc8cd459.png)

results in this output which shows there is no context provided:

![image](https://user-images.githubusercontent.com/90011823/218115271-c20162f7-6db6-432c-8565-1b43ca94f8a8.png)

I'm assuming the lack of a context is what is causing the `Entity` not to be displayed.  Is that correct?  Is importing a component from a third-party package possible?

Other notes:
- I'm using Next JS version 12.3.4 for the project
- I'm using Vite version 4.1.1 to bundle the package that has my `Entity`
- The component importing the `TestEntity` component above looks like this:

```javascript
import { TestEntity } from 'resium-import-test'
// ... other imports 

const MapComponents = () => {
    const { viewer } = useCesium()

    // this console.log outputs a valid Viewer
    console.log({ viewer })

    useEffect(() => {
        if (viewer) {
            console.log({ viewer })
            viewer.scene.mode = SceneMode.SCENE2D
        }
    }, [viewer])

    return (
        <>
            <TestEntity viewer={viewer} />

            // The Entity below works as expected
            {/* <Entity description="test" name="VA" point={{ pixelSize: 10 }} position={Cartesian3.fromDegrees(-76.17, 36.56, 100)} /> */}
        </>
    )
}

// make this a client-side only component
const NoSsrMapComponents = dynamic(async () => MapComponents, { ssr: false })

export default NoSsrMapComponents
```

**Comment by rot1024** [comment]
Are you using it in the wrong way? We recommend that you read the documentation carefully.

Entity must be used within a VIewer or CesiumWidget component.

```jsx
<Viewer>
  <Entity />
</Viewer>
```
