### ISSUE TITLE
EntityDescription timeout may not be sufficient

### ISSUE THREAD

**Issue by connormanning** [reearth/resium#604]
There is a [hard-coded 10ms timeout](https://github.com/reearth/resium/blob/e5cdc93c12684c0584a7919e1ce4662dba310700/src/EntityDescription/EntityDescription.ts#L66-L74) which is used before setting the `InfoBox` body after an Entity is activated.  However I've found this to be unreliable, and for the InfoBox body often not to render.  The top bar with the Entity name, camera, and `X` button renders just fine, but is missing the body.

This is easy to reproduce by setting the `Viewer`'s `targetFrameRate` to a low value like 5 frames per second.

**Comment by rot1024** [comment]
Try new version v1.17.0!
