### ISSUE TITLE
Cesium 1.106.1 deprications

### ISSUE THREAD

**Issue by Kai-W** [reearth/resium#606]
If i use resium 1.16.1 and cesium 1.106.1 i get deprication Warnings e.g.
for Cesium3DTileset wit url and onReady Function:
"options.url was deprecated in CesiumJS 1.104.  It will be removed in CesiumJS 1.107.  Use CesiumTerrainProvider.fromIonAssetId or CesiumTerrainProvider.fromUrl instead."
"Cesium3DTileset constructor parameter options.url was deprecated in CesiumJS 1.104. It will be removed in 1.107. Use Cesium3DTileset.fromUrl instead."
Additionally support for the new attributes like baseLayer and terrain on the View object would be nice.

**Comment by rot1024** [comment]
Thank you for report. PR is welcome.

**Comment by Kai-W** [comment]
'The patchnotes of Cesium 1.104 https://github.com/CesiumGS/cesium/releases/tag/1.104 says the readyPromise pattern is deprecated. Beeing quite new to Cesium and Resium i don't think i can provide a suitable solution.

**Comment by prusswan** [comment]
Until resium is updated, do not use it with CesiumJS >= 1.107

**Comment by KaWaite** [comment]
This will be fixed in [this PR](https://github.com/reearth/resium/pull/609). Thank you!

**Comment by Kai-W** [comment]
Thanks for the PR. But i don't like that this Issue was closed while the PR is not merged. It should only be closed if the PR got merged.

**Comment by rot1024** [comment]
Try new version v1.17.0!
