### ISSUE TITLE
"createWorldTerrain" was deprecated

### ISSUE THREAD

**Issue by federicomarcantognini** [reearth/resium#607]
Hi all,
I get this warning in my console:
`createWorldTerrain was deprecated in CesiumJS 1.104.  It will be removed in CesiumJS 1.107.  Use createWorldTerrainAsync instead.`

which is triggered by this in my code:
`const viewerTerrainProvider = Cesium.createWorldTerrain();`
And within Viewer:
`terrainProvider={viewerTerrainProvider}`

the Async triggers an issue so I cannot change it. Hints?

**Comment by KaWaite** [comment]
This will be fixed in the [Cesium upgrade PR](https://github.com/reearth/resium/pull/609). Should be merged in the next couple days

**Comment by rot1024** [comment]
Try new version v1.17.0!
