### ISSUE TITLE
Declaration file not found

### ISSUE THREAD

**Issue by erikuusitalo** [reearth/resium#611]
# Error
Could not find a declaration file for module 'resium'. '<my path>/cesium-demo/node_modules/resium/dist/resium.mjs' implicitly has an 'any' type. There are types at '<my path>/cesium-demo/node_modules/resium/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'resium' library may need to update its package.json or typings. [7016]

# Reproduce
Installed using guide: https://resium.reearth.io/installation#5-vite

# Code
```tsx
import { Viewer } from 'resium' # ERROR MESSAGE

export function Map() {
  return (
    <>
      <Viewer />
    </>  
  )
}
```

# Versions
```json
{
  "dependencies": {
    "cesium": "^1.107.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "resium": "^1.16.1"
  },
  "devDependencies": {
    "@types/react": "^18.0.37",
    "@types/react-dom": "^18.0.11",
    "@typescript-eslint/eslint-plugin": "^5.59.0",
    "@typescript-eslint/parser": "^5.59.0",
    "@vitejs/plugin-react-swc": "^3.0.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.38.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.0.2",
    "vite": "^4.3.9",
    "vite-plugin-cesium": "^1.2.22"
  }

}
```

**Comment by Fedec96** [comment]
Hey, maybe this is quite similar to #603. Can you help me figuring out how to export the types of the components' properties? I don't even know where to start.

**Comment by rot1024** [comment]
Try new version v1.17.0!
